add_newline = false

format = "$all"

[aws]
disabled = true
[gcloud]
disabled = true

[character]
vicmd_symbol = "[V](bold green) "

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
truncate_to_repo = false
format = " [ðŸ“‚ $path]($style)[$read_only]($read_only_style) "

[nodejs]
format = "via [îœ˜ $version](bold green) "

[username]
style_user = "white bold"
style_root = "black bold"
format = "ï€‡ [$user]($style) "
disabled = false
show_always = true

[battery]
disabled = false
show_always = true




